name: Create Development Builds

jobs:
  android_development_build:
    name: Build Android
    type: build
    params:
      platform: android
      profile: development

  ios_device_development_build:
    name: Build iOS Device
    type: build
    params:
      platform: ios
      profile: development